// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "title": "Hello!",
    "userName": "User Name : {userName}"
  }
};
export default messages;